services:
  web:
    build: .
    container_name: flask_app
    restart: always
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      POSTGRES_USER: guest_user
      POSTGRES_PASSWORD: guest_password
      POSTGRES_DB: pa_db

  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: guest_user
      POSTGRES_PASSWORD: guest_password
      POSTGRES_DB: pa_db
    ports:
      - "5432:5432"
    # volumes:
      # - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
