version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=pa_db

  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: pa_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
